export const template1 = [
    {
      shiftRight: 5,
      shiftDown: 5,
      spread: 0,
      blur: 0,
      opacity: 100,
      inset: false,
      color: "#289FED",
    },
    {
      shiftRight: 10,
      shiftDown: 10,
      spread: 0,
      blur: 0,
      opacity: 100,
      inset: false,
      color: "#5FB8FF",
    },
    {
      shiftRight: 15,
      shiftDown: 15,
      spread: 0,
      blur: 0,
      opacity: 100,
      inset: false,
      color: "#A1D8FF",
    },
    {
      shiftRight: 20,
      shiftDown: 20,
      spread: 0,
      blur: 0,
      opacity: 100,
      inset: false,
      color: "#CAE6FF",
    },
    {
      shiftRight: 25,
      shiftDown: 25,
      spread: 0,
      blur: 0,
      opacity: 100,
      inset: false,
      color: "#E1EEFF",
    },
  ];

export const template2 = [
    {
      shiftRight: -1,
      shiftDown: 0,
      spread: 0,
      blur: 4,
      opacity: 100,
      inset: false,
      color: "#FFFFFF",
    },
    {
      shiftRight: -2,
      shiftDown: 0,
      spread: 0,
      blur: 10,
      opacity: 100,
      inset: false,
      color: "#FFFF00",
    },
    {
      shiftRight: -10,
      shiftDown: 0,
      spread: 0,
      blur: 20,
      opacity: 100,
      inset: false,
      color: "#FF8000",
    },
    {
      shiftRight: -18,
      shiftDown: 0,
      spread: 0,
      blur: 40,
      opacity: 100,
      inset: false,
      color: "#FF0000",
    },
  ];

export const initialBoxShadow = {
    shiftRight: 0,
    shiftDown: 0,
    spread: 0,
    blur: 5,
    opacity: 20,
    inset: false,
    color: "#000000",
  }